### ISSUE TITLE
【確認待ち】管理画面からアップデートできるようにしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/impress-wordpress-plugin#1]
最新のリリースタグがあったらアップデートするように plugin update checker など設定

※ 大嶋さんが作業する場合、どんな感じでやるのかは RICK さんに伝授してもらってください。

3月中旬までにできれればOK

**Comment by drill-lancer** [comment]
いきまーす

**Comment by drill-lancer** [comment]
@kurudrive 
main ブランチに実装しておきました。
アップデータは GitHub の Release から取得するようになってます。
こちらでも行いましたが一応リリースデータの確認もお願いします。

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございますー！
